### ISSUE TITLE
Does not work inside a .love

### ISSUE THREAD

**Issue by davisdude** [adonaac/thomas#1]
When you put this inside of a .love you get an error. Maybe it could be backed inside of the save directory?

```
Error

main.lua:3: module 'Utilities.thomas.input' not found:
no field package.preload['Utilities.thomas.input']
no file 
blah blah blah blah blah...
```

**Comment by a327ex** [comment]
Could you show me your main file? Or whatever Utilities.thomas.input is or is supposed to be.

**Comment by davisdude** [comment]
Sure: It's here all the same here except in main.lua I use `Input = require 'Utilities.thomas.input'`
https://github.com/davisdude/New-Base
It runs fine in an unzipped file, but in a .love it gets an error.

**Comment by a327ex** [comment]
I have no idea what could be causing this other than maybe a typo (it runs fine here), have you tried Utilities.thomas.Input, with capital I? The Input.lua file starts like that.

**Comment by davisdude** [comment]
Completely my bad... you're right. 
I thought it could be because it being zipped inside of the .love
Absolutely my fault.
