### ISSUE TITLE
input:pressed and input:released broken

### ISSUE THREAD

**Issue by npinochet** [adonaac/thomas#11]
Since I updated to new version, my game broke and after some debugging I encounter that input:pressed() and input:released() seems to be broken. input:pressed() acts the same as input:down() and input:released() just returns nothing. 

EDIT: after some tests I found that love.update and all the other callbacks gets overwritten. so when boipushy registers the callbacks, it does nothing, they gets overwritten with the actual function on the main.lua file.

**Comment by a327ex** [comment]
Are you still calling input:update? If you are you shouldn't do that.

**Comment by npinochet** [comment]
Yeah, I double checked, I'm not calling input:update.

**Comment by a327ex** [comment]
Could you paste me your code?

**Comment by npinochet** [comment]
``` lua
io.stdout:setvbuf("no")
input = require("input")()
function love.load()
    input:bind("a","action")
end
function love.update(dt)
    print(input:pressed("action"))
    print(input:released("action"))
end
```

EDIT: I think I get it now, I can't creat an input object when I require it, I need to do it in love.load, I didn't knew that. Thanks anyway.
