### ISSUE TITLE
not all mouse codes included

### ISSUE THREAD

**Issue by robinvd** [adonaac/thomas#18]
if i add a print here
```
function Input:mousepressed(x, y, button)
    print(button)
    self.state[button_to_key[button]] = true
end
```
my mouse buttons cause it to print 'l' and 'r', and then crash because those are not in the button_to_key table.

```
r
Error: libs/Input.lua:258: table index is nil
stack traceback:
        libs/Input.lua:258: in function <libs/Input.lua:256>
        libs/Input.lua:62: in function <libs/Input.lua:60>
        [string "boot.lua"]:425: in function <[string "boot.lua"]:399>
        [C]: in function 'xpcall
```

i'm using nixos

**Comment by davisdude** [comment]
Which version of LOVE are you using? Since 0.10.0, those have been changed to be `1`, `2`, etc. (see the [wiki](http://love2d.org/wiki/MouseConstant)). 

It looks like the library is only compatible with 0.10.0 and beyond (see `button_to_key`)

**Comment by robinvd** [comment]
Ah thank you, im using 0.9.1. maybe this can be included in the readme?

**Comment by robinvd** [comment]
Ah thank you, im using 0.9.1. maybe this can be included in the readme?

**Comment by robinvd** [comment]
Ah thank you, im using 0.9.1. maybe this can be included in the readme?

**Comment by davisdude** [comment]
I don't know if @SSYGEN intends to add compatibility, but if not, just replace `1` with `'l'`, `2` to `'r'`, etc. 

Alternatively you could upgrade to the latest version of LOVE.
