### ISSUE TITLE
input:pressed doesn't work

### ISSUE THREAD

**Issue by npinochet** [adonaac/thomas#6]
Your example  `if input:pressed('print') then print(1) end` actually doesn't work, input:pressed only works when the key has been bind with a function, but not with a name.

**Comment by a327ex** [comment]
That's false. Paste your full code because you must be doing something wrong.

**Comment by npinochet** [comment]
Oops, I'm really sorry, I didn't notice the part where you need to put input:update() at the end on love.update. sorry.
edit: just to leave something constructive, the key "space" is written twice on the table all_keys.
