### ISSUE TITLE
Cannot bind ' ' (space) key

### ISSUE THREAD

**Issue by davisdude** [adonaac/thomas#8]

**Comment by a327ex** [comment]
In the all_keys table, change the first "space" for " "

**Comment by davisdude** [comment]
When you use the word 'space' it also fails.

**Comment by a327ex** [comment]
???? Change the first "space" in all_keys for " " and input:bind(' ', 'action_name') will work.

**Comment by davisdude** [comment]
Oh, I thought you were telling me that if I wanted it like standard LOVE I would have to do it myself. Never mind
